version: "3.3"
services:
  bank_consumer:
    build: .
    image: bank_consumer
    container_name: bank_consumer
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /home/user/.volumes/bank_consumer/source:/source:rw
    tty: true
    working_dir: /source
    command: ["python", "main.py"]