version: "3.3"
services:
  telegram_consumer:
    build: .
    image: telegram_consumer
    container_name: telegram_consumer
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /home/user/.volumes/telegram_consumer/source:/source:rw
    tty: true
    working_dir: /source
    command: ["python", "main.py"]